
service: basic-serverless-lambda
provider:
  name: aws
  runtime: nodejs14.x
  #stage: dev
  region: ap-south-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    name: generateRandomNumber